#2-a)

In [ ]:
import numpy as np

# 주어진 데이터
D = np.array([[-1, 1],
              [0, 1],
              [1, 1],
              [1, 0]])

# input
X = D[:, 0].reshape(-1, 1)

# target
t = D[:, 1].reshape(-1, 1)

X = np.hstack((X, np.ones_like(X)))

inv=np.linalg.inv(X.T.dot(X))
temp=X.T.dot(t)
w=inv.dot(temp)

In [ ]:
w

array([[-0.27272727],
       [ 0.81818182]])

In [ ]:
w[0][0] #w_1

-0.2727272727272727

In [ ]:
w[1][0] #w_0

0.8181818181818183

In [ ]:
cnt=len(w)
for i in w:
  print(f"w_{cnt-1}:",i)
  cnt-=1

w_1: [-0.27272727]
w_0: [0.81818182]


#2-b)

In [ ]:
import numpy as np

# 주어진 데이터
D = np.array([[1, 1],
              [0, 1],
              [-1, 1],
              [-1, 0]])

# input
X = D[:, 0].reshape(-1, 1)

# target
t = D[:, 1].reshape(-1, 1)


X = np.hstack((X, np.ones_like(X)))
inv=np.linalg.inv(X.T.dot(X))
temp=X.T.dot(t)
w=inv.dot(temp)

In [ ]:
w

array([[0.27272727],
       [0.81818182]])

In [ ]:
w[0][0] #w_1

0.2727272727272727

In [ ]:
w[1][0] #w_0

0.8181818181818183

In [ ]:
cnt=len(w)
for i in w:
  print(f"w_{cnt-1}:",i)
  cnt-=1

w_1: [0.27272727]
w_0: [0.81818182]


# 2-c)

In [ ]:
def h2(x):
  return x**2

def h1(x):
  return x

def h0(x):
  return np.full_like(x, 1)

# 주어진 데이터
D = np.array([[-1, 1],
              [0, 1],
              [1, 1],
              [1, 0]])
# input
X = D[:, 0].reshape(-1, 1)

# target
t = D[:, 1].reshape(-1, 1)

H = np.column_stack((h2(X),h1(X),h0(X)))
print("H: ",H)

inv=np.linalg.inv(H.T.dot(H))
temp=H.T.dot(t)
w=inv.dot(temp)

H:  [[ 1 -1  1]
 [ 0  0  1]
 [ 1  1  1]
 [ 1  1  1]]


In [ ]:
cnt=len(w)
for i in w:
  print(f"w_{cnt-1}:",i)
  cnt-=1

w_2: [-0.25]
w_1: [-0.25]
w_0: [1.]


# 2-d)

In [ ]:
def h2(x):
  return np.exp(-(x+1)**2)


def h1(x):
  return np.exp(-x**2)

def h0(x):
  return np.full_like(x, 1)

# 주어진 데이터
D = np.array([[-1, 1],
              [0, 1],
              [1, 1],
              [1, 0]])
# input
X = D[:, 0].reshape(-1, 1)

# target
t = D[:, 1].reshape(-1, 1)

H = np.column_stack((h2(X),h1(X),h0(X)))

inv=np.linalg.inv(H.T.dot(H))
temp=H.T.dot(t)
w=inv.dot(temp)

In [ ]:
H

array([[1.        , 0.36787944, 1.        ],
       [0.36787944, 1.        , 1.        ],
       [0.01831564, 0.36787944, 1.        ],
       [0.01831564, 0.36787944, 1.        ]])

In [ ]:
t

array([[1],
       [1],
       [1],
       [0]])

In [ ]:
w

array([[0.50932868],
       [0.50932868],
       [0.30329977]])

In [ ]:
cnt=len(w)
for i in w:
  print(f"w_{cnt-1}:",i)
  cnt-=1

w_2: [0.50932868]
w_1: [0.50932868]
w_0: [0.30329977]


# 3-a)

In [ ]:
import numpy as np

# 주어진 데이터를 NumPy 배열로 표현
data = np.array([
    [2, 200, 4, 27, 30000],
    [5, 150, 3, 35, 20000],
    [3, 180, 4, 25, 25000],
    [1, 230, 2, 10, 21000],
    [5, 180, 5, 40, 38000],
    [4, 210, 3, 30, 31000]
])

print(data)



[[    2   200     4    27 30000]
 [    5   150     3    35 20000]
 [    3   180     4    25 25000]
 [    1   230     2    10 21000]
 [    5   180     5    40 38000]
 [    4   210     3    30 31000]]


In [ ]:
age= data[:,0]
hp= data[:,1]
brand= data[:,2]
mpg= data[:,3]
price=data[:,4]

In [ ]:
price.reshape(-1, 1)

array([[30000],
       [20000],
       [25000],
       [21000],
       [38000],
       [31000]])

In [ ]:
def h3(hp,age):
  return hp/age

def h2(hp):
  return np.log(hp)


def h1(brand,mpg):
  return brand * np.sqrt(mpg)




In [ ]:
# target
t = price.reshape(-1, 1)
H = np.column_stack((h3(hp,age),h2(hp),h1(brand,mpg)))

#for w_0
ones_column = np.ones((H.shape[0], 1))
# 1로 구성된 열 벡터를 원래의 행렬에 추가
H= np.hstack((H, ones_column))


inv=np.linalg.inv(H.T.dot(H))
temp=H.T.dot(t)
w=inv.dot(temp)

In [ ]:
H

array([[100.        ,   5.29831737,  20.78460969,   1.        ],
       [ 30.        ,   5.01063529,  17.74823935,   1.        ],
       [ 60.        ,   5.19295685,  20.        ,   1.        ],
       [230.        ,   5.43807931,   6.32455532,   1.        ],
       [ 36.        ,   5.19295685,  31.6227766 ,   1.        ],
       [ 52.5       ,   5.34710753,  16.43167673,   1.        ]])

In [ ]:
w

array([[-2.92265305e+01],
       [ 3.81727020e+04],
       [ 7.99597840e+02],
       [-1.85350179e+05]])

In [ ]:
cnt=len(w)
for i in w:
  print(f"w_{cnt-1}:",i)
  cnt-=1

w_3: [-29.22653055]
w_2: [38172.70195694]
w_1: [799.5978402]
w_0: [-185350.17920467]
